# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2dfc1b17093f111e3f670a8d20b0df926addea4b285981383e00a692957bcaba4d669ec1f99e2317e738b9542ac9a52d200a1e661c2d3a422a12c723ca501552

test:
  secret_key_base: eeb8dd645041fd7c0e446a4d99d268a364feb168f11786330f4f7036c9202db417f79eb1dd1747d4009716f1b4d40e6848a2aef7ea243449e8a4943966c24d8b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
